<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>UI.App</StartupObject>
    <ApplicationIcon>Common\Resources\Assets\Icons\app_taskbar_icon.ico</ApplicationIcon>
    <AssemblyName>Asset Ops</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Common\Resources\Assets\Cursors\grab.cur" />
    <None Remove="Common\Resources\Assets\Cursors\grabbing.cur" />
    <None Remove="Common\Resources\Assets\Icons\app_logo_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\chinese_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_add_trade_image_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_calculator_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_delete_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_edit_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_folder_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_home_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_long_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_mistakes_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_notes_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_quit_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_rezize_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_rezize_fullscreen_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_short_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_theme_dark_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_theme_light_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\dark_theme_settings_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\delete_cross_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\english_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\folder_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\french_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\german_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\italian_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\japanese_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_add_trade_image_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_calculator_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_delete_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_edit_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_folder_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_home_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_long_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_mistakes_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_notes_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_quit_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_rezize_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_rezize_fullscreen_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_short_button_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_theme_dark_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_theme_light_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\light_theme_settings_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\portuguese_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\russian_icon.png" />
    <None Remove="Common\Resources\Assets\Icons\spanish_icon.png" />
    <None Remove="DataBase.db" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Common\Resources\Assets\Icons\app_taskbar_icon.ico" />
    <Content Include="DataBase.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Common\Resources\Assets\Icons\dark_add_trade_image_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_delete_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_edit_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_folder_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_mistakes_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_notes_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_short_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\delete_cross_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_add_trade_image_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_delete_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_edit_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_folder_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_mistakes_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_notes_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_short_button_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts" Version="0.9.7" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MainModule\MainModule.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Common\Resources\Assets\Cursors\grab.cur" />
    <Resource Include="Common\Resources\Assets\Cursors\grabbing.cur" />
    <Resource Include="Common\Resources\Assets\Icons\app_logo_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\chinese_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_calculator_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_home_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_long_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_quit_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_rezize_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_rezize_fullscreen_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_theme_dark_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_theme_light_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\dark_theme_settings_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\english_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\french_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\german_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\italian_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\japanese_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_calculator_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_home_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_long_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_quit_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_rezize_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_rezize_fullscreen_button_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_theme_dark_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_theme_light_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\light_theme_settings_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Common\Resources\Assets\Icons\portuguese_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\russian_icon.png" />
    <Resource Include="Common\Resources\Assets\Icons\spanish_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="AppSettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="AppSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="AppSettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
